In [109]:
import pandas as pd

In [110]:
pd.__version__

'3.0.3'

In [111]:
carInfoTable = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [112]:
print(type(carInfoTable))

<class 'pandas.DataFrame'>

In [113]:
carInfoTable.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [114]:
carInfoTable.info()

<class 'pandas.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   engine_displacement  9704 non-null   int64
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64
 6   origin               9704 non-null   str
 7   fuel_type            9704 non-null   str
 8   drivetrain           9704 non-null   str
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), str(3)
memory usage: 834.1 KB

In [115]:
carInfoTable.describe()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,num_doors,fuel_efficiency_mpg
count,9704.000000,9222.000000,8996.000000,9704.000000,8774.000000,9704.000000,9202.000000,9704.000000
mean,199.708368,3.962481,149.657292,3001.280993,15.021928,2011.484027,-0.006412,14.985243
std,49.455319,1.999323,29.879555,497.894860,2.510339,6.659808,1.048162,2.556468
min,10.000000,0.000000,37.000000,952.681761,6.000000,2000.000000,-4.000000,6.200971
25%,170.000000,3.000000,130.000000,2666.248985,13.300000,2006.000000,-1.000000,13.267459
50%,200.000000,4.000000,149.000000,2993.226296,15.000000,2012.000000,0.000000,15.006037
75%,230.000000,5.000000,170.000000,3334.957039,16.700000,2017.000000,1.000000,16.707965
max,380.000000,13.000000,271.000000,4739.077089,24.300000,2023.000000,4.000000,25.967222

In [116]:
carInfoTable['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel']
Length: 2, dtype: str

In [117]:
carInfoTable[carInfoTable['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

In [118]:
median_before = carInfoTable['horsepower'].median()
print(median_before)

149.0

In [119]:
carInfoTable['horsepower'].mode()
most_frequent = df['horsepower'].mode()[0]
print(most_frequent)

152.0

In [120]:
carInfoTable['horsepower'] = carInfoTable['horsepower'].fillna(most_frequent)
median_after = carInfoTable['horsepower'].median()
print(median_after)

152.0

In [121]:
carInfoTable['origin'] == 'Asia'

0       False
1       False
2       False
3       False
4       False
        ...
9699    False
9700    False
9701    False
9702    False
9703     True
Name: origin, Length: 9704, dtype: bool

In [122]:
carInfoTable.loc[carInfoTable['origin'] == 'Asia', ['vehicle_weight', 'model_year']]

      vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [123]:
asia = carInfoTable.loc[carInfoTable['origin'] == 'Asia', ['vehicle_weight', 'model_year']]

In [124]:
asiaFirst7 = asia.head(7)

In [125]:
X = asiaFirst7.values
print(X)

[[2714.21930965 2016.        ]
 [2783.86897424 2010.        ]
 [3582.68736772 2007.        ]
 [2231.8081416  2011.        ]
 [2659.43145076 2016.        ]
 [2844.22753389 2014.        ]
 [3761.99403819 2019.        ]]

In [126]:
XTX = X.T @ X
print(XTX)

[[62248334.33150762 41431216.5073268 ]
 [41431216.5073268  28373339.        ]]

In [127]:
import numpy as np
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)

[[ 5.71497081e-07 -8.34509443e-07]
 [-8.34509443e-07  1.25380877e-06]]

In [128]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]
w = XTX_inv @ X.T @ y
print(w)
print(w.sum())

[0.01386421 0.5049067 ]
0.5187709081074016